<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('products')->insert([

           
[
'name' => 'Jeruk Nipis',
'scientific_name' => 'Citrus aurantifolia',
'description' => 'Jeruk Nipis (Citrus aurantifolia) is a shrub plant suitable for conservation and ecological restoration.',
'price' => 100000,
'image_url' => '/product_images/jeruk_nipis.jpg',
'plant_type' => 'Shrub',
'estimated_carbon' => '5-10 kg CO₂/year',
'benefits' => 'Butterfly Habitat',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Jeruk Kingkit',
'scientific_name' => 'Triphasia trifolia',
'description' => 'Jeruk Kingkit (Triphasia trifolia) is a shrub plant suitable for conservation and ecological restoration.',
'price' => 100000,
'image_url' => '/product_images/jeruk_kingkit.jpg',
'plant_type' => 'Shrub',
'estimated_carbon' => '5-10 kg CO₂/year',
'benefits' => 'Butterfly Habitat',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Alpukat',
'scientific_name' => 'Persea americana',
'description' => 'Alpukat (Persea americana) is a tree plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => '/product_images/alpukat.jpg',
'plant_type' => 'Tree',
'estimated_carbon' => '30-50 kg CO₂/year',
'benefits' => 'Butterfly Habitat',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Sirsak',
'scientific_name' => 'Annona muricata',
'description' => 'Sirsak (Annona muricata) is a tree plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => '/product_images/sirsak.jpg',
'plant_type' => 'Tree',
'estimated_carbon' => '30-50 kg CO₂/year',
'benefits' => 'Butterfly Habitat',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Srikaya',
'scientific_name' => 'Annona squamosa',
'description' => 'Srikaya (Annona squamosa) is a tree plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => '/product_images/srikaya.jpg',
'plant_type' => 'Tree',
'estimated_carbon' => '30-50 kg CO₂/year',
'benefits' => 'Butterfly Habitat',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Glodokan',
'scientific_name' => 'Polyalthia longifolia',
'description' => 'Glodokan (Polyalthia longifolia) is a tree plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => '/product_images/glodokan.jpg',
'plant_type' => 'Tree',
'estimated_carbon' => '30-50 kg CO₂/year',
'benefits' => 'Butterfly Habitat',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Saga Pohon',
'scientific_name' => 'Adenanthera pavonia',
'description' => 'Saga Pohon (Adenanthera pavonia) is a tree plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => '/product_images/saga_pohon.jpg',
'plant_type' => 'Tree',
'estimated_carbon' => '30-50 kg CO₂/year',
'benefits' => 'Butterfly Habitat',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Sirih Hutan',
'scientific_name' => 'Thottea tomentosa',
'description' => 'Sirih Hutan (Thottea tomentosa) is a shrub plant suitable for conservation and ecological restoration.',
'price' => 100000,
'image_url' => '/product_images/sirih_hutan.jpg',
'plant_type' => 'Shrub',
'estimated_carbon' => '5-10 kg CO₂/year',
'benefits' => 'Butterfly Habitat',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Johar',
'scientific_name' => 'Cassia siamea',
'description' => 'Johar (Cassia siamea) is a shrub plant suitable for conservation and ecological restoration.',
'price' => 100000,
'image_url' => '/product_images/johar.jpg',
'plant_type' => 'Shrub',
'estimated_carbon' => '5-10 kg CO₂/year',
'benefits' => 'Butterfly Habitat',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Johar Semak',
'scientific_name' => 'Cassia biflora',
'description' => 'Johar Semak (Cassia biflora) is a shrub plant suitable for conservation and ecological restoration.',
'price' => 100000,
'image_url' => '/product_images/johar_semak.jpg',
'plant_type' => 'Shrub',
'estimated_carbon' => '5-10 kg CO₂/year',
'benefits' => 'Butterfly Habitat',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Rumput Manan',
'scientific_name' => 'Cloeme rutidosperma',
'description' => 'Rumput Manan (Cloeme rutidosperma) is a herb plant suitable for conservation and ecological restoration.',
'price' => 100000,
'image_url' => '/product_images/rumput_manan.jpg',
'plant_type' => 'Herb',
'estimated_carbon' => '2-4 kg CO₂/year',
'benefits' => 'Butterfly Habitat',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Ketepeng',
'scientific_name' => 'Cassia alata',
'description' => 'Ketepeng (Cassia alata) is a shrub plant suitable for conservation and ecological restoration.',
'price' => 100000,
'image_url' => '/product_images/ketepeng.jpg',
'plant_type' => 'Shrub',
'estimated_carbon' => '5-10 kg CO₂/year',
'benefits' => 'Butterfly Habitat',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Cempaka Kuning',
'scientific_name' => 'Michelia champaca',
'description' => 'Cempaka Kuning (Michelia champaca) is a tree plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => '/product_images/cempaka_kuning.jpg',
'plant_type' => 'Tree',
'estimated_carbon' => '30-50 kg CO₂/year',
'benefits' => 'Butterfly Habitat',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Jarak',
'scientific_name' => 'Ricinus communis',
'description' => 'Jarak (Ricinus communis) is a shrub plant suitable for conservation and ecological restoration.',
'price' => 100000,
'image_url' => '/product_images/jarak.jpg',
'plant_type' => 'Shrub',
'estimated_carbon' => '5-10 kg CO₂/year',
'benefits' => 'Butterfly Habitat',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Asystasia',
'scientific_name' => 'Asystasia intrusa',
'description' => 'Asystasia (Asystasia intrusa) is a herb plant suitable for conservation and ecological restoration.',
'price' => 100000,
'image_url' => '/product_images/asystasia.jpg',
'plant_type' => 'Herb',
'estimated_carbon' => '2-4 kg CO₂/year',
'benefits' => 'Butterfly Habitat',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Aristolochiae',
'scientific_name' => 'Aristolochiae tagala',
'description' => 'Aristolochiae (Aristolochiae tagala) is a climber plant suitable for conservation and ecological restoration.',
'price' => 100000,
'image_url' => '/product_images/aristolochiae_tagala.jpg',
'plant_type' => 'Climber',
'estimated_carbon' => '2-4 kg CO₂/year',
'benefits' => 'Butterfly Habitat',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Aristolochiae',
'scientific_name' => 'Aristolochiae faveolata',
'description' => 'Aristolochiae (Aristolochiae faveolata) is a climber plant suitable for conservation and ecological restoration.',
'price' => 100000,
'image_url' => '/product_images/aristolochiae_faveolata.jpg',
'plant_type' => 'Climber',
'estimated_carbon' => '2-4 kg CO₂/year',
'benefits' => 'Butterfly Habitat',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Serut',
'scientific_name' => 'Cerbera odollam',
'description' => 'Serut (Cerbera odollam) is a tree plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => '/product_images/serut.jpg',
'plant_type' => 'Tree',
'estimated_carbon' => '30-50 kg CO₂/year',
'benefits' => 'Butterfly Habitat',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Bunga Mentega',
'scientific_name' => 'Nerium oleaner',
'description' => 'Bunga Mentega (Nerium oleaner) is a shrub plant suitable for conservation and ecological restoration.',
'price' => 100000,
'image_url' => '/product_images/bunga_mentega.jpg',
'plant_type' => 'Shrub',
'estimated_carbon' => '5-10 kg CO₂/year',
'benefits' => 'Butterfly Habitat',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Daun Wungu',
'scientific_name' => 'Gratophyllum pictum',
'description' => 'Daun Wungu (Gratophyllum pictum) is a shrub plant suitable for conservation and ecological restoration.',
'price' => 100000,
'image_url' => '/product_images/daun_wungu.jpg',
'plant_type' => 'Shrub',
'estimated_carbon' => '5-10 kg CO₂/year',
'benefits' => 'Butterfly Habitat',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Rumput Babi',
'scientific_name' => 'Synedrella nodiflora',
'description' => 'Rumput Babi (Synedrella nodiflora) is a herb plant suitable for conservation and ecological restoration.',
'price' => 100000,
'image_url' => '/product_images/rumput_babi.jpg',
'plant_type' => 'Herb',
'estimated_carbon' => '2-4 kg CO₂/year',
'benefits' => 'Butterfly Habitat',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Jelatang Ayam',
'scientific_name' => 'Laportea inerrupta',
'description' => 'Jelatang Ayam (Laportea inerrupta) is a shrub plant suitable for conservation and ecological restoration.',
'price' => 100000,
'image_url' => '/product_images/jelatang_ayam.jpg',
'plant_type' => 'Shrub',
'estimated_carbon' => '5-10 kg CO₂/year',
'benefits' => 'Butterfly Habitat',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Widuri',
'scientific_name' => 'Calotropis giganthea',
'description' => 'Widuri (Calotropis giganthea) is a shrub plant suitable for conservation and ecological restoration.',
'price' => 100000,
'image_url' => '/product_images/widuri.jpg',
'plant_type' => 'Shrub',
'estimated_carbon' => '5-10 kg CO₂/year',
'benefits' => 'Butterfly Habitat',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Lobi-Lobi',
'scientific_name' => 'Flacourtia inermis roxl.',
'description' => 'Lobi-Lobi (Flacourtia inermis roxl.) is a tree plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => '/product_images/lobi-lobi.jpg',
'plant_type' => 'Tree',
'estimated_carbon' => '30-50 kg CO₂/year',
'benefits' => 'Butterfly Habitat',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Ruku-Ruku Tetikus',
'scientific_name' => 'Clausena excavata',
'description' => 'Ruku-Ruku Tetikus (Clausena excavata) is a tree plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => '/product_images/ruku_ruku_tetikus.jpg',
'plant_type' => 'Tree',
'estimated_carbon' => '30-50 kg CO₂/year',
'benefits' => 'Butterfly Habitat',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Ruku-Ruku Asli',
'scientific_name' => 'Murraya koenigi',
'description' => 'Ruku-Ruku Asli (Murraya koenigi) is a tree plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => '/product_images/ruku_ruku_asli.jpg',
'plant_type' => 'Tree',
'estimated_carbon' => '30-50 kg CO₂/year',
'benefits' => 'Butterfly Habitat',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Apama',
'scientific_name' => 'Apama thomentosa',
'description' => 'Apama (Apama thomentosa) is a shrub plant suitable for conservation and ecological restoration.',
'price' => 100000,
'image_url' => '/product_images/apama.jpg',
'plant_type' => 'Shrub',
'estimated_carbon' => '5-10 kg CO₂/year',
'benefits' => 'Butterfly Habitat',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Kelapa',
'scientific_name' => 'Cocos nucifera',
'description' => 'Kelapa (Cocos nucifera) is a tree plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => '/product_images/kelapa.jpg',
'plant_type' => 'Tree',
'estimated_carbon' => '15-25 kg CO₂/year',
'benefits' => 'Butterfly Habitat',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Ketapang',
'scientific_name' => 'Terminalia catappa',
'description' => 'Ketapang (Terminalia catappa) is a tree plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => '/product_images/ketapang.jpg',
'plant_type' => 'Tree',
'estimated_carbon' => '30-50 kg CO₂/year',
'benefits' => 'Butterfly Habitat',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Nona Makan Sirih',
'scientific_name' => 'Mussaenda spp.',
'description' => 'Nona Makan Sirih (Mussaenda spp.) is a climber plant suitable for conservation and ecological restoration.',
'price' => 100000,
'image_url' => '/product_images/nona_makan_sirih.jpg',
'plant_type' => 'Climber',
'estimated_carbon' => '2-4 kg CO₂/year',
'benefits' => 'Butterfly Habitat',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Bungur',
'scientific_name' => 'Lagerstromia soeciosa',
'description' => 'Bungur (Lagerstromia soeciosa) is a tree plant suitable for conservation and ecological restoration.',
'price' => 25000,
'image_url' => '/product_images/bungur.jpg',
'plant_type' => 'Tree',
'estimated_carbon' => '30-50 kg CO₂/year',
'benefits' => 'Butterfly Habitat',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Tanaman Rambat Zemeros',
'scientific_name' => 'Host Zemeros flegyas',
'description' => 'Tanaman Rambat Zemeros (Host Zemeros flegyas) is a shrub plant suitable for conservation and ecological restoration.',
'price' => 15000,
'image_url' => '/product_images/tanaman_rambat_zemeros.jpg',
'plant_type' => 'Shrub',
'estimated_carbon' => '5-10 kg CO₂/year',
'benefits' => 'Butterfly Habitat',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Pauh-Pauh',
'scientific_name' => 'Melicoppe spp.',
'description' => 'Pauh-Pauh (Melicoppe spp.) is a tree plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => '/product_images/melicope_spp_pauh_pauh.jpg',
'plant_type' => 'Tree',
'estimated_carbon' => '30-50 kg CO₂/year',
'benefits' => 'Butterfly Habitat',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Bunga Asoka',
'scientific_name' => 'Ixora javanica',
'description' => 'Bunga Asoka (Ixora javanica) is a shrub plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => '/product_images/bunga_asoka.jpg',
'plant_type' => 'Shrub',
'estimated_carbon' => '5-10 kg CO₂/year',
'benefits' => 'Butterfly Habitat',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Bunga Pagoda',
'scientific_name' => 'Clerodendrum paniculatum',
'description' => 'Bunga Pagoda (Clerodendrum paniculatum) is a shrub plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => '/product_images/bunga_pagoda.jpg',
'plant_type' => 'Shrub',
'estimated_carbon' => '5-10 kg CO₂/year',
'benefits' => 'Butterfly Habitat',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Jengger Ayam',
'scientific_name' => 'Celosia argentea',
'description' => 'Jengger Ayam (Celosia argentea) is a shrub plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => '/product_images/bunga_jengger_ayam.jpg',
'plant_type' => 'Shrub',
'estimated_carbon' => '5-10 kg CO₂/year',
'benefits' => 'Butterfly Habitat',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Bunga Tahi - Ayam',
'scientific_name' => 'Tagates erecta',
'description' => 'Bunga Tahi - Ayam (Tagates erecta) is a shrub plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => '/product_images/bunga_tahi_ayam.jpg',
'plant_type' => 'Shrub',
'estimated_carbon' => '5-10 kg CO₂/year',
'benefits' => 'Butterfly Habitat',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Kembang Pacar',
'scientific_name' => 'Impatiens balsamina',
'description' => 'Kembang Pacar (Impatiens balsamina) is a shrub plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => '/product_images/bunga_pacar.jpg',
'plant_type' => 'Shrub',
'estimated_carbon' => '5-10 kg CO₂/year',
'benefits' => 'Butterfly Habitat',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Cente Manis',
'scientific_name' => 'Lantana camara',
'description' => 'Cente Manis (Lantana camara) is a shrub plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => '/product_images/bunga_cente_manis.jpg',
'plant_type' => 'Shrub',
'estimated_carbon' => '5-10 kg CO₂/year',
'benefits' => 'Butterfly Habitat',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Jarong',
'scientific_name' => 'Stachypheta indica',
'description' => 'Jarong (Stachypheta indica) is a shrub plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => '/product_images/bunga_jarong.jpg',
'plant_type' => 'Shrub',
'estimated_carbon' => '5-10 kg CO₂/year',
'benefits' => 'Butterfly Habitat',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Kembang Pukul Empat',
'scientific_name' => 'Mirabilis jalapa',
'description' => 'Kembang Pukul Empat (Mirabilis jalapa) is a shrub plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => '/product_images/bunga_pukul_empat.jpg',
'plant_type' => 'Shrub',
'estimated_carbon' => '5-10 kg CO₂/year',
'benefits' => 'Butterfly Habitat',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Kembang Kertas',
'scientific_name' => 'Zinnia sp.',
'description' => 'Kembang Kertas (Zinnia sp.) is a shrub plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => '/product_images/bunga_kertas.jpg',
'plant_type' => 'Shrub',
'estimated_carbon' => '5-10 kg CO₂/year',
'benefits' => 'Butterfly Habitat',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Kembang Merak',
'scientific_name' => 'Caesalpinnia pulcherrima',
'description' => 'Kembang Merak (Caesalpinnia pulcherrima) is a shrub plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => '/product_images/bunga_kembang_merak.jpg',
'plant_type' => 'Shrub',
'estimated_carbon' => '5-10 kg CO₂/year',
'benefits' => 'Butterfly Habitat',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Orok-Orok',
'scientific_name' => 'Crotalaria sriata',
'description' => 'Orok-Orok (Crotalaria sriata) is a shrub plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => '/product_images/bunga_orok-orok.jpg',
'plant_type' => 'Shrub',
'estimated_carbon' => '5-10 kg CO₂/year',
'benefits' => 'Butterfly Habitat',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Kembang Sepatu',
'scientific_name' => 'Hibiscus rosa-sinensis',
'description' => 'Kembang Sepatu (Hibiscus rosa-sinensis) is a shrub plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => '/product_images/bunga_kembang_sepatu.jpg',
'plant_type' => 'Shrub',
'estimated_carbon' => '5-10 kg CO₂/year',
'benefits' => 'Butterfly Habitat',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Cantik Manis',
'scientific_name' => 'Cosmos sulphurous cav',
'description' => 'Cantik Manis (Cosmos sulphurous cav) is a shrub plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => '/product_images/bunga_cantik_manis.jpg',
'plant_type' => 'Shrub',
'estimated_carbon' => '5-10 kg CO₂/year',
'benefits' => 'Butterfly Habitat',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Taiwan Beauty',
'scientific_name' => 'Cuphea hysopifolia',
'description' => 'Taiwan Beauty (Cuphea hysopifolia) is a shrub plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => '/product_images/bunga_taiwan_beauty.jpg',
'plant_type' => 'Shrub',
'estimated_carbon' => '5-10 kg CO₂/year',
'benefits' => 'Butterfly Habitat',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Seruni',
'scientific_name' => 'Widelia sp.',
'description' => 'Seruni (Widelia sp.) is a shrub plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => '/product_images/bunga_seruni.jpg',
'plant_type' => 'Shrub',
'estimated_carbon' => '5-10 kg CO₂/year',
'benefits' => 'Butterfly Habitat',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Kaliandra Merah',
'scientific_name' => 'Calliandra haemathocephala',
'description' => 'Kaliandra Merah (Calliandra haemathocephala) is a tree plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => '/product_images/bunga_kaliandra_merah.jpg',
'plant_type' => 'Tree',
'estimated_carbon' => '30-50 kg CO₂/year',
'benefits' => 'Butterfly Habitat',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Kaliandra Merah Putih',
'scientific_name' => 'Calliandra surinamensis',
'description' => 'Kaliandra Merah Putih (Calliandra surinamensis) is a tree plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => '/product_images/bunga_kaliandra_merah_putih.jpg',
'plant_type' => 'Tree',
'estimated_carbon' => '30-50 kg CO₂/year',
'benefits' => 'Butterfly Habitat',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Kumis Kucing',
'scientific_name' => 'Oritthosiphon aristatus',
'description' => 'Kumis Kucing (Oritthosiphon aristatus) is a shrub plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => '/product_images/bunga_kumis_kucing.jpg',
'plant_type' => 'Shrub',
'estimated_carbon' => '5-10 kg CO₂/year',
'benefits' => 'Butterfly Habitat',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Kembang Kancing',
'scientific_name' => 'Gomphrena globosa',
'description' => 'Kembang Kancing (Gomphrena globosa) is a shrub plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => '/product_images/bunga_kembang_kancing.jpg',
'plant_type' => 'Shrub',
'estimated_carbon' => '5-10 kg CO₂/year',
'benefits' => 'Butterfly Habitat',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Micromelum',
'scientific_name' => 'Micromelum minutum',
'description' => 'Micromelum (Micromelum minutum) is a tree plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => '/product_images/bunga_micromelum.jpg',
'plant_type' => 'Tree',
'estimated_carbon' => '30-50 kg CO₂/year',
'benefits' => 'Butterfly Habitat',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Keruing',
'scientific_name' => 'Dipterocarpus alatus',
'description' => 'Keruing (Dipterocarpus alatus) is a tree plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => '/product_images/bunga_keruing.jpg',
'plant_type' => 'Tree',
'estimated_carbon' => '50-80 kg CO₂/year',
'benefits' => 'Primate & bird habitat; squirrel food',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Keruing Kancing',
'scientific_name' => 'Dipterocarpus hasseltii',
'description' => 'Keruing Kancing (Dipterocarpus hasseltii) is a tree plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => '/product_images/bunga_keruing_kancing.jpg',
'plant_type' => 'Tree',
'estimated_carbon' => '45-75 kg CO₂/year',
'benefits' => 'Parent tree for nocturnal birds',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Keruing Kaloi',
'scientific_name' => 'Dipterocarpus gracilis',
'description' => 'Keruing Kaloi (Dipterocarpus gracilis) is a tree plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => '/product_images/bunga_keruing_kaloi.jpg',
'plant_type' => 'Tree',
'estimated_carbon' => '40-70 kg CO₂/year',
'benefits' => 'Critical for Orangutans; bird nests',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Meranti Bakau',
'scientific_name' => 'Shorea leprosula',
'description' => 'Meranti Bakau (Shorea leprosula) is a tree plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => '/product_images/bunga_meranti_bakau.jpg',
'plant_type' => 'Tree',
'estimated_carbon' => '50-85 kg CO₂/year',
'benefits' => 'Primate food; owl bird habitat',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Meranti Rawa',
'scientific_name' => 'Shorea parvifolia',
'description' => 'Meranti Rawa (Shorea parvifolia) is a tree plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => '/product_images/bunga_meranti_rawa.jpg',
'plant_type' => 'Tree',
'estimated_carbon' => '45-75 kg CO₂/year',
'benefits' => 'Wildlife corridor',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Meranti Payung',
'scientific_name' => 'Shorea macrophylla',
'description' => 'Meranti Payung (Shorea macrophylla) is a tree plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => '/product_images/bunga_meranti_payung.jpg',
'plant_type' => 'Tree',
'estimated_carbon' => '40-70 kg CO₂/year',
'benefits' => 'Sumatran elephant food',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Kapur',
'scientific_name' => 'Dryobalanops lanceolata',
'description' => 'Kapur (Dryobalanops lanceolata) is a tree plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => '/product_images/bunga_kapur.jpg',
'plant_type' => 'Tree',
'estimated_carbon' => '45-70 kg CO₂/year',
'benefits' => 'Habitat insectivorous birds',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Merawan',
'scientific_name' => 'Hopea odorata',
'description' => 'Merawan (Hopea odorata) is a tree plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => '/product_images/bunga_merawan.jpg',
'plant_type' => 'Tree',
'estimated_carbon' => '35-60 kg CO₂/year',
'benefits' => 'Mammal corridor tree',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Mersawa',
'scientific_name' => 'Anisoptera costata',
'description' => 'Mersawa (Anisoptera costata) is a tree plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => '/product_images/mersawa.jpg',
'plant_type' => 'Tree',
'estimated_carbon' => '40-65 kg CO₂/year',
'benefits' => 'Squirrel and pangolin food',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Resak Rawa',
'scientific_name' => 'Vatica pumila',
'description' => 'Resak Rawa (Vatica pumila) is a tree plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => '/product_images/resak_rawa.jpg',
'plant_type' => 'Tree',
'estimated_carbon' => '35-55 kg CO₂/year',
'benefits' => 'Swamp water bird habitat',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Beringin',
'scientific_name' => 'Ficus benjamina',
'description' => 'Beringin (Ficus benjamina) is a tree plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => '/product_images/beringin.jpg',
'plant_type' => 'Tree',
'estimated_carbon' => '25-45 kg CO₂/year',
'benefits' => 'Critical for 50+ bird species; bat nest',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Ara Sren',
'scientific_name' => 'Ficus virens',
'description' => 'Ara Sren (Ficus virens) is a tree plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => '/product_images/ara_sren.jpg',
'plant_type' => 'Tree',
'estimated_carbon' => '30-50 kg CO₂/year',
'benefits' => 'Frugivorous bird & primate food',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Ara',
'scientific_name' => 'Ficus religiosa',
'description' => 'Ara (Ficus religiosa) is a tree plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => '/product_images/ara.jpg',
'plant_type' => 'Tree',
'estimated_carbon' => '25-40 kg CO₂/year',
'benefits' => 'Butterfly & bird habitat',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Ara Jawa',
'scientific_name' => 'Ficus hispida',
'description' => 'Ara Jawa (Ficus hispida) is a tree plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => '/product_images/ara_jawa.jpg',
'plant_type' => 'Tree',
'estimated_carbon' => '20-35 kg CO₂/year',
'benefits' => 'Monitor lizard and bird food',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Jati',
'scientific_name' => 'Tectona grandis',
'description' => 'Jati (Tectona grandis) is a tree plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => '/product_images/jati.jpg',
'plant_type' => 'Tree',
'estimated_carbon' => '35-55 kg CO₂/year',
'benefits' => 'Tree bats & squirrels',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Angsana',
'scientific_name' => 'Pterocarpus indicus',
'description' => 'Angsana (Pterocarpus indicus) is a tree plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => '/product_images/angsana.jpg',
'plant_type' => 'Tree',
'estimated_carbon' => '45-75 kg CO₂/year',
'benefits' => 'Water bird habitat',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Pohon Kari',
'scientific_name' => 'Murraya koenigii',
'description' => 'Pohon Kari (Murraya koenigii) is a tree plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => '/product_images/pohon_kari.jpg',
'plant_type' => 'Tree',
'estimated_carbon' => '5–15 kg CO₂/year ',
'benefits' => 'Used as a culinary spice (curry leaves), rich in antioxidants, supports digestion, and has traditional medicinal uses.',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Gin Berry',
'scientific_name' => 'Glycosmis penthapilla',
'description' => 'Gin berry (Glycosmis penthapilla) is a tree plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => '/product_images/gin_berry.jpg',
'plant_type' => 'Tree',
'estimated_carbon' => '3–10 kg CO₂/year',
'benefits' => 'traditional medicine',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Eucalyptus',
'scientific_name' => 'Eucalyptus deglupta',
'description' => 'Eucalyptus (Eucalyptus deglupta) is a tree plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => '/product_images/eucalyptus.jpg',
'plant_type' => 'Tree',
'estimated_carbon' => '50-80 kg CO₂/year',
'benefits' => 'Honey tree for bees & birds',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Durian',
'scientific_name' => 'Durio zibethinus',
'description' => 'Durian (Durio zibethinus) is a tree plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => '/product_images/durian.jpg',
'plant_type' => 'Tree',
'estimated_carbon' => '30-50 kg CO₂/year',
'benefits' => 'Critical for primates (Orangutans, monkeys); birds',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Sukun',
'scientific_name' => 'Artocarpus altilis',
'description' => 'Sukun (Artocarpus altilis) is a tree plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => '/product_images/sukun.jpg',
'plant_type' => 'Tree',
'estimated_carbon' => '20-35 kg CO₂/year',
'benefits' => 'Fruit bat food',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Mangga',
'scientific_name' => 'Mangifera indica',
'description' => 'Mangga (Mangifera indica) is a tree plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => '/product_images/mangga.jpg',
'plant_type' => 'Tree',
'estimated_carbon' => '20-35 kg CO₂/year',
'benefits' => 'Squirrel & monkey food',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Rambutan',
'scientific_name' => 'Nephelium lappaceum',
'description' => 'Rambutan (Nephelium lappaceum) is a tree plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => '/product_images/rambutan.jpg',
'plant_type' => 'Tree',
'estimated_carbon' => '15-30 kg CO₂/year',
'benefits' => 'Frugivorous bird food',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Jambu Biji',
'scientific_name' => 'Psidium guajava',
'description' => 'Jambu Biji (Psidium guajava) is a tree plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => '/product_images/jambu_biji.jpg',
'plant_type' => 'Tree',
'estimated_carbon' => '15-25 kg CO₂/year',
'benefits' => 'Small mammal food; butterflies',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Jambu Air',
'scientific_name' => 'Syzygium aqueum',
'description' => 'Jambu Air (Syzygium aqueum) is a tree plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => '/product_images/jambu_air.jpg',
'plant_type' => 'Tree',
'estimated_carbon' => '15-25 kg CO₂/year',
'benefits' => 'Bird & bat food',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Duwet',
'scientific_name' => 'Syzygium cumini',
'description' => 'Duwet (Syzygium cumini) is a tree plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => '/product_images/duwet.jpg',
'plant_type' => 'Tree',
'estimated_carbon' => '20-30 kg CO₂/year',
'benefits' => 'Pangolin food',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Belimbing Wuluh',
'scientific_name' => 'Averrhoa bilimbi',
'description' => 'Belimbing Wuluh (Averrhoa bilimbi) is a tree plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => '/product_images/belimbing_wuluh.jpg',
'plant_type' => 'Tree',
'estimated_carbon' => '10-20 kg CO₂/year',
'benefits' => 'Bird & butterfly food',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Belimbing',
'scientific_name' => 'Averrhoa carambola',
'description' => 'Belimbing (Averrhoa carambola) is a tree plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => '/product_images/belimbing.jpg',
'plant_type' => 'Tree',
'estimated_carbon' => '10-20 kg CO₂/year',
'benefits' => 'Nectar for butterflies',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Pisang',
'scientific_name' => 'Musa spp.',
'description' => 'Pisang (Musa spp.) is a tree plant suitable for conservation and ecological restoration.',
'price' => 100000,
'image_url' => '/product_images/pisang.jpg',
'plant_type' => 'Large Herb',
'estimated_carbon' => '10-18 kg CO₂/year',
'benefits' => 'Pangolin feeds on birds, butterflies',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Kayu Manis',
'scientific_name' => 'Cinnamomum verum',
'description' => 'Kayu Manis (Cinnamomum verum) is a tree plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => '/product_images/kayu_manis.jpg',
'plant_type' => 'Tree',
'estimated_carbon' => '20-30 kg CO₂/year',
'benefits' => 'Habitat of parasitoid insects',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Andaliman',
'scientific_name' => 'Zanthoxylum rhetsa',
'description' => 'Andaliman (Zanthoxylum rhetsa) is a tree plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => '/product_images/andaliman.jpg',
'plant_type' => 'Tree',
'estimated_carbon' => '15-25 kg CO₂/year',
'benefits' => 'Bird feed',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Kenanga',
'scientific_name' => 'Cananga odorata',
'description' => 'Kenanga (Cananga odorata) is a tree plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => '/product_images/kenanga.jpg',
'plant_type' => 'Tree',
'estimated_carbon' => '15-25 kg CO₂/year',
'benefits' => 'Nectar for butterflies & birds',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Cendana',
'scientific_name' => 'Santalum album',
'description' => 'Cendana (Santalum album) is a tree plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => '/product_images/cendana.jpg',
'plant_type' => 'Tree',
'estimated_carbon' => '12-20 kg CO₂/year',
'benefits' => 'Habitat of rare butterflies',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Aren',
'scientific_name' => 'Arenga pinnata',
'description' => 'Aren (Arenga pinnata) is a tree plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => '/product_images/aren.jpg',
'plant_type' => 'Palm',
'estimated_carbon' => '15-25 kg CO₂/year',
'benefits' => 'Tarsier food; squirrel habitat; nectar',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Kelapa',
'scientific_name' => 'Cocos nucifera',
'description' => 'Kelapa (Cocos nucifera) is a tree plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => '/product_images/kelapa.jpg',
'plant_type' => 'Palm',
'estimated_carbon' => '20-35 kg CO₂/year',
'benefits' => 'Habitat for nesting birds (magpie robins, starlings); insects',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Lontar',
'scientific_name' => 'Borassus flabellifer',
'description' => 'Lontar (Borassus flabellifer) is a tree plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => '/product_images/lontar.jpg',
'plant_type' => 'Palm',
'estimated_carbon' => '15-25 kg CO₂/year',
'benefits' => "Civet food; bird's nest",
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Nipah',
'scientific_name' => 'Nypa fruticans',
'description' => 'Nipah (Nypa fruticans) is a tree plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => '/product_images/nipah.jpg',
'plant_type' => 'Swamp Palm',
'estimated_carbon' => '25-45 kg CO₂/year',
'benefits' => 'Habitat for water birds & swamp insects',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Pinang',
'scientific_name' => 'Areca catechu',
'description' => 'Pinang (Areca catechu) is a tree plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => '/product_images/pinang.jpg',
'plant_type' => 'Palm',
'estimated_carbon' => '10-20 kg CO₂/year',
'benefits' => 'Small mammal habitat',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Bambu Tali',
'scientific_name' => 'Gigantochloa apus',
'description' => 'Bambu Tali (Gigantochloa apus) is a bamboo plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => '/product_images/bambu_tali.jpg',
'plant_type' => 'Bamboo',
'estimated_carbon' => 'High',
'benefits' => 'Pangolin & squirrel habitat; mammal corridor',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Bambu Ater',
'scientific_name' => 'Gigantochloa verticillata',
'description' => 'Bambu Ater (Gigantochloa verticillata) is a bamboo plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => '/product_images/bambu_ater.jpg',
'plant_type' => 'Bamboo',
'estimated_carbon' => 'High',
'benefits' => 'Bird & bat habitat',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Bambu Betung',
'scientific_name' => 'Dendrocalamus asper',
'description' => 'Bambu Betung (Dendrocalamus asper) is a bamboo plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => '/product_images/bambu_betung.jpg',
'plant_type' => 'Bamboo',
'estimated_carbon' => 'High',
'benefits' => 'Monitor lizard & insect habitat',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Bambu Kuning',
'scientific_name' => 'Bambusa vulgaris',
'description' => 'Bambu Kuning (Bambusa vulgaris) is a bamboo plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => '/product_images/bambu_kuning.jpg',
'plant_type' => 'Bamboo',
'estimated_carbon' => 'High',
'benefits' => 'Bird habitat (land)',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Bambu Reng',
'scientific_name' => 'Schizostachyum brachycladum',
'description' => 'Bambu Reng (Schizostachyum brachycladum) is a bamboo plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => '/product_images/bambu_reng.jpg',
'plant_type' => 'Bamboo',
'estimated_carbon' => 'High',
'benefits' => 'Butterfly & bird habitat',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Nusa Indah',
'scientific_name' => 'Mussaenda spp.',
'description' => 'Nusa Indah (Mussaenda spp.) is a shrub plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => '/product_images/nusa_indah.jpg',
'plant_type' => 'Shrub',
'estimated_carbon' => '5-10 kg CO₂/year',
'benefits' => 'Butterfly host plant (Ornithoptera)',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Asoka',
'scientific_name' => 'Ixora spp.',
'description' => 'Asoka (Ixora spp.) is a shrub plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => 'product_images/asoka.jpg',
'plant_type' => 'Shrub',
'estimated_carbon' => '5-10 kg CO₂/year',
'benefits' => 'Host & food plant butterflies (Papilionidae)',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Girang',
'scientific_name' => 'Leea indica',
'description' => 'Girang (Leea indica) is a shrub plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => 'product_images/girang.jpg',
'plant_type' => 'Shrub',
'estimated_carbon' => '4-8 kg CO₂/year',
'benefits' => 'Food source for frugivorous birds',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Senggani',
'scientific_name' => 'Melastoma malabathricum',
'description' => 'Senggani (Melastoma malabathricum) is a shrub plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => 'product_images/senggani.jpg',
'plant_type' => 'Shrub',
'estimated_carbon' => '3-7 kg CO₂/year',
'benefits' => 'Food source for birds; Butterfly habitat',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Akar Kupang',
'scientific_name' => 'Rubus moluccanus',
'description' => 'Akar Kupang (Rubus moluccanus) is a shrub plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => 'product_images/akar_kupang.jpg',
'plant_type' => 'Shrub',
'estimated_carbon' => '3-6 kg CO₂/year',
'benefits' => 'Food source for small mammals & birds',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Kopi Hutan',
'scientific_name' => 'Psychotria spp.',
'description' => 'Kopi Hutan (Psychotria spp.) is a shrub plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => 'product_images/kopi_hutan.jpg',
'plant_type' => 'Shrub',
'estimated_carbon' => '4-8 kg CO₂/year',
'benefits' => 'Habitat for forest birds',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Kembang Bugang',
'scientific_name' => 'Clerodendrum spp.',
'description' => 'Kembang Bugang (Clerodendrum spp.) is a shrub plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => 'product_images/kembang_bugang.jpg',
'plant_type' => 'Shrub',
'estimated_carbon' => '5-10 kg CO₂/year',
'benefits' => 'Nectar for butterflies & birds',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Tanjung',
'scientific_name' => 'Stachytarpheta indica',
'description' => 'Tanjung (Stachytarpheta indica) is a shrub plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => 'product_images/tanjung.jpg',
'plant_type' => 'Shrub',
'estimated_carbon' => '3-6 kg CO₂/year',
'benefits' => 'Nectar for butterflies',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Bulu Ayam',
'scientific_name' => 'Eupatorium odoratum',
'description' => 'Bulu Ayam (Eupatorium odoratum) is a shrub plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => 'product_images/bulu_ayam.jpg',
'plant_type' => 'Shrub',
'estimated_carbon' => '4-8 kg CO₂/year',
'benefits' => 'Habitat for parasitoid insects',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Tembelekan',
'scientific_name' => 'Lantana camara',
'description' => 'Tembelekan (Lantana camara) is a shrub plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => 'product_images/tembelekan.jpg',
'plant_type' => 'Shrub',
'estimated_carbon' => '3-5 kg CO₂/year',
'benefits' => 'Nectar for butterflies',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Ki Asem',
'scientific_name' => 'Sambucus javanica',
'description' => 'Ki Asem (Sambucus javanica) is a shrub plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => 'product_images/ki_asem.jpg',
'plant_type' => 'Shrub',
'estimated_carbon' => '5-10 kg CO₂/year',
'benefits' => 'Bird feed',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Kaliandra',
'scientific_name' => 'Calliandra calothyrsus',
'description' => 'Kaliandra (Calliandra calothyrsus) is a shrub plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => 'product_images/kaliandra.jpg',
'plant_type' => 'Shrub',
'estimated_carbon' => '8-15 kg CO₂/year',
'benefits' => 'Nitrogen fixer; bird feed & small mammal habitat',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Gamal',
'scientific_name' => 'Gliricidia sepium',
'description' => 'Gamal (Gliricidia sepium) is a shrub plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => 'product_images/gamal.jpg',
'plant_type' => 'Shrub',
'estimated_carbon' => '8-15 kg CO₂/year',
'benefits' => 'Nitrogen fixer; host vanilla; deer feed',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Lamtoro',
'scientific_name' => 'Leucaena leucocephala',
'description' => 'Lamtoro (Leucaena leucocephala) is a shrub plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => 'product_images/lamtoro.jpg',
'plant_type' => 'Shrub',
'estimated_carbon' => '7-14 kg CO₂/year',
'benefits' => 'Small mammal & bird feed; nitrogen fixer',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Dadap',
'scientific_name' => 'Erythrina variegata',
'description' => 'Dadap (Erythrina variegata) is a shrub plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => 'product_images/dadap.jpg',
'plant_type' => 'Shrub',
'estimated_carbon' => '8-15 kg CO₂/year',
'benefits' => 'Nectar for birds; nitrogen fixer',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Turi',
'scientific_name' => 'Sesbania grandiflora',
'description' => 'Turi (Sesbania grandiflora) is a shrub plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => 'product_images/turi.jpg',
'plant_type' => 'Shrub',
'estimated_carbon' => '6-12 kg CO₂/year',
'benefits' => 'Bird feed & pollinator habitat',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Mengkudu',
'scientific_name' => 'Morinda citrifolia',
'description' => 'Mengkudu (Morinda citrifolia) is a shrub plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => 'product_images/mengkudu.jpg',
'plant_type' => 'Shrub',
'estimated_carbon' => '4-8 kg CO₂/year',
'benefits' => 'Luwak feed & bird feed; butterfly host plant',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Sirih Hutan',
'scientific_name' => 'Piper aduncum',
'description' => 'Sirih Hutan (Piper aduncum) is a shrub plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => 'product_images/sirih_hutan.jpg',
'plant_type' => 'Shrub',
'estimated_carbon' => '3-6 kg CO₂/year',
'benefits' => 'Deer feed',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Sirih',
'scientific_name' => 'Piper betle',
'description' => 'Sirih (Piper betle) is a tree plant suitable for conservation and ecological restoration.',
'price' => 150000,
'image_url' => 'product_images/sirih.jpg',
'plant_type' => 'Shrub',
'estimated_carbon' => '2-5 kg CO₂/year',
'benefits' => 'Habitat for small insects',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Jahe-Jahean',
'scientific_name' => 'Zingiber spp.',
'description' => 'Jahe-Jahean (Zingiber spp.) is a herb plant suitable for conservation and ecological restoration.',
'price' => 100000,
'image_url' => 'product_images/jahe_jahean.jpg',
'plant_type' => 'Herb',
'estimated_carbon' => '2-4 kg CO₂/year',
'benefits' => 'Nectar for butterflies & birds',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Hoya',
'scientific_name' => 'Hoya spp.',
'description' => 'Hoya (Hoya spp.) is a climber plant suitable for conservation and ecological restoration.',
'price' => 100000,
'image_url' => 'product_images/hoya.jpg',
'plant_type' => 'Climber',
'estimated_carbon' => '5-8 kg CO₂/year',
'benefits' => 'Butterfly habitat',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Markisa/Rambusa',
'scientific_name' => 'Passiflora spp.',
'description' => 'Markisa/Rambusa (Passiflora spp.) is a climber plant suitable for conservation and ecological restoration.',
'price' => 100000,
'image_url' => 'product_images/markisa.jpg',
'plant_type' => 'Climber',
'estimated_carbon' => '3-6 kg CO₂/year',
'benefits' => 'Butterfly habitat',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Rambusa',
'scientific_name' => 'Adenia spp.',
'description' => 'Rambusa (Adenia spp.) is a climber plant suitable for conservation and ecological restoration.',
'price' => 100000,
'image_url' => 'product_images/rambusa.jpg',
'plant_type' => 'Climber',
'estimated_carbon' => '2-5 kg CO₂/year',
'benefits' => 'Butterfly habitat',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Begawan',
'scientific_name' => 'Cissus spp.',
'description' => 'Begawan (Cissus spp.) is a climber plant suitable for conservation and ecological restoration.',
'price' => 12000,
'image_url' => 'product_images/begawan.jpg',
'plant_type' => 'Climber',
'estimated_carbon' => '2-4 kg CO₂/year',
'benefits' => 'Bird feed & small mammal habitat',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Akar Setawar',
'scientific_name' => 'Smilax spp.',
'description' => 'Akar Setawar (Smilax spp.) is a climber plant suitable for conservation and ecological restoration.',
'price' => 100000,
'image_url' => '/product_images/akar_setawar.jpg',
'plant_type' => 'Climber',
'estimated_carbon' => '2-4 kg CO₂/year',
'benefits' => 'Small mammal habitat',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Rotan',
'scientific_name' => 'Calamus spp.',
'description' => 'Rotan (Calamus spp.) is a tree plant suitable for conservation and ecological restoration.',
'price' => 100000,
'image_url' => 'product_images/rotan.jpg',
'plant_type' => 'Climber',
'estimated_carbon' => '8-15 kg CO₂/year',
'benefits' => 'Deer habitat & bird feed',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Rotan Tikus',
'scientific_name' => 'Korthalsia spp.',
'description' => 'Rotan Tikus (Korthalsia spp.) is a climber plant suitable for conservation and ecological restoration.',
'price' => 100000,
'image_url' => 'product_images/rotan_tikus.jpg',
'plant_type' => 'Climber',
'estimated_carbon' => '6-12 kg CO₂/year',
'benefits' => 'Small mammal habitat',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Akar Takut',
'scientific_name' => 'Flagellaria indica',
'description' => 'Akar Takut (Flagellaria indica) is a climber plant suitable for conservation and ecological restoration.',
'price' => 100000,
'image_url' => '/product_images/akar_takut.jpg',
'plant_type' => 'Climber',
'estimated_carbon' => '2-4 kg CO₂/year',
'benefits' => 'Butterfly Habitat',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Ubi Rambat',
'scientific_name' => 'Ipomoea batatas',
'description' => 'Ubi Rambat (Ipomoea batatas) is a climber plant suitable for conservation and ecological restoration.',
'price' => 100000,
'image_url' => 'product_images/ubi_rambat.jpg',
'plant_type' => 'Climber',
'estimated_carbon' => '2-4 kg CO₂/year',
'benefits' => 'Wild boar feed',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Lengkuas',
'scientific_name' => 'Alpinia galanga',
'description' => 'Lengkuas (Alpinia galanga) is a herb plant suitable for conservation and ecological restoration.',
'price' => 100000,
'image_url' => 'product_images/lengkuas.jpg',
'plant_type' => 'Herb',
'estimated_carbon' => '2-4 kg CO₂/year',
'benefits' => 'Nectar for butterflies',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Kunyit',
'scientific_name' => 'Curcuma longa',
'description' => 'Kunyit (Curcuma longa) is a herb plant suitable for conservation and ecological restoration.',
'price' => 100000,
'image_url' => 'product_images/kunyit.jpg',
'plant_type' => 'Herb',
'estimated_carbon' => '1-3 kg CO₂/year',
'benefits' => 'Habitat soil insects',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Kecombrang',
'scientific_name' => 'Etlingera elatior',
'description' => 'Kecombrang (Etlingera elatior) is a herb plant suitable for conservation and ecological restoration.',
'price' => 100000,
'image_url' => 'product_images/kecombrang.jpg',
'plant_type' => 'Herb',
'estimated_carbon' => '2-4 kg CO₂/year',
'benefits' => 'Nectar for hummingbirds',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Pisang-Pisangan',
'scientific_name' => 'Heliconia spp.',
'description' => 'Pisang-Pisangan (Heliconia spp.) is a herb plant suitable for conservation and ecological restoration.',
'price' => 100000,
'image_url' => 'product_images/pisang_pisangan.jpg',
'plant_type' => 'Herb',
'estimated_carbon' => '2-5 kg CO₂/year',
'benefits' => 'Butterfly Habitat & bird habitat',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Pacing',
'scientific_name' => 'Costus speciosus',
'description' => 'Pacing (Costus speciosus) is a herb plant suitable for conservation and ecological restoration.',
'price' => 100000,
'image_url' => 'product_images/pacing.jpg',
'plant_type' => 'Herb',
'estimated_carbon' => '2-4 kg CO₂/year',
'benefits' => 'Nectar for butterflies',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Bengkarung',
'scientific_name' => 'Thalia geniculata',
'description' => 'Bengkarung (Thalia geniculata) is a tree plant suitable for conservation and ecological restoration.',
'price' => 100000,
'image_url' => 'product_images/bengkarung.jpg',
'plant_type' => 'Marsh herb',
'estimated_carbon' => '3-6 kg CO₂/year',
'benefits' => 'Habitat aquatic birds & insects',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Jukut/Jerami',
'scientific_name' => 'Cyperus spp.',
'description' => 'Jukut/Jerami (Cyperus spp.) is a herb plant suitable for conservation and ecological restoration.',
'price' => 100000,
'image_url' => 'product_images/jerami.jpg',
'plant_type' => 'Herb',
'estimated_carbon' => '1-3 kg CO₂/year',
'benefits' => 'Habitat small mammals & insects',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Alang-Alang',
'scientific_name' => 'Imperata cylindrica',
'description' => 'Alang-Alang (Imperata cylindrica) is a herb plant suitable for conservation and ecological restoration.',
'price' => 100000,
'image_url' => 'product_images/alang_alang.jpg',
'plant_type' => 'Herb',
'estimated_carbon' => '2-5 kg CO₂/year',
'benefits' => 'Habitat small mammals & insects',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Prumpung',
'scientific_name' => 'Phragmites karka',
'description' => 'Prumpung (Phragmites karka) is a tree plant suitable for conservation and ecological restoration.',
'price' => 100000,
'image_url' => '/product_images/prumpung.jpg',
'plant_type' => 'Marsh herb',
'estimated_carbon' => '2-5 kg CO₂/year',
'benefits' => 'Habitat aquatic birds & insects',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],
[
'name' => 'Rumput Hutan',
'scientific_name' => 'Scleria sumatrensis',
'description' => 'Rumput Hutan (Scleria sumatrensis) is a herb plant suitable for conservation and ecological restoration.',
'price' => 100000,
'image_url' => '/product_images/rumput_hutan.jpg',
'plant_type' => 'Herb',
'estimated_carbon' => '1-3 kg CO₂/year',
'benefits' => 'Habitat soil insects & butterflies',
'soft_delete' => 0,
'created_at' => Carbon::now(),
'updated_at' => Carbon::now(),
],


        ]);
    }
}
