<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('products')->insert([

            [
                'name' => 'Jeruk Nipis ',
                'scientific_name' => 'Citrus aurantifolia ',
                'description' => 'Jeruk Nipis  is a shrub plant suitable for conservation and ecological restoration.',
                'price' => 15000,
                'image_url' => '',
                'plant_type' => 'Shrub',
                'estimated_carbon' => '5-10 kg CO₂/th',
                'benefits' => 'Butterfly habitat',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Jeruk Kingkit ',
                'scientific_name' => 'Triphasia trifolia ',
                'description' => 'Jeruk Kingkit  is a shrub plant suitable for conservation and ecological restoration.',
                'price' => 15000,
                'image_url' => '',
                'plant_type' => 'Shrub',
                'estimated_carbon' => '5-10 kg CO₂/th',
                'benefits' => 'Butterfly habitat',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Alpukat ',
                'scientific_name' => 'Persea americana ',
                'description' => 'Alpukat  is a tree plant suitable for conservation and ecological restoration.',
                'price' => 25000,
                'image_url' => '',
                'plant_type' => 'Tree',
                'estimated_carbon' => '30-50 kg CO₂/th',
                'benefits' => 'Butterfly habitat',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Sirsak',
                'scientific_name' => 'Annona muricata ',
                'description' => 'Sirsak is a tree plant suitable for conservation and ecological restoration.',
                'price' => 25000,
                'image_url' => '',
                'plant_type' => 'Tree',
                'estimated_carbon' => '30-50 kg CO₂/th',
                'benefits' => 'Butterfly habitat',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Srikaya ',
                'scientific_name' => 'Annona squamosa',
                'description' => 'Srikaya  is a tree plant suitable for conservation and ecological restoration.',
                'price' => 25000,
                'image_url' => '',
                'plant_type' => 'Tree',
                'estimated_carbon' => '30-50 kg CO₂/th',
                'benefits' => 'Butterfly habitat',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Glodokan',
                'scientific_name' => 'Polyalthia longifolia',
                'description' => 'Glodokan is a tree plant suitable for conservation and ecological restoration.',
                'price' => 25000,
                'image_url' => '',
                'plant_type' => 'Tree',
                'estimated_carbon' => '30-50 kg CO₂/th',
                'benefits' => 'Butterfly habitat',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Saga Pohon',
                'scientific_name' => 'Adenanthera pavonia',
                'description' => 'Saga Pohon is a tree plant suitable for conservation and ecological restoration.',
                'price' => 25000,
                'image_url' => '',
                'plant_type' => 'Tree',
                'estimated_carbon' => '30-50 kg CO₂/th',
                'benefits' => 'Butterfly habitat',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Sirih Hutan ',
                'scientific_name' => 'Thottea tomentosa ',
                'description' => 'Sirih Hutan  is a shrub plant suitable for conservation and ecological restoration.',
                'price' => 15000,
                'image_url' => '',
                'plant_type' => 'Shrub',
                'estimated_carbon' => '5-10 kg CO₂/th',
                'benefits' => 'Butterfly habitat',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Johar ',
                'scientific_name' => 'Cassia siamea',
                'description' => 'Johar  is a shrub plant suitable for conservation and ecological restoration.',
                'price' => 15000,
                'image_url' => '',
                'plant_type' => 'Shrub',
                'estimated_carbon' => '5-10 kg CO₂/th',
                'benefits' => 'Butterfly habitat',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Johar Semak ',
                'scientific_name' => 'Cassia biflora ',
                'description' => 'Johar Semak  is a shrub plant suitable for conservation and ecological restoration.',
                'price' => 15000,
                'image_url' => '',
                'plant_type' => 'Shrub',
                'estimated_carbon' => '5-10 kg CO₂/th',
                'benefits' => 'Butterfly habitat',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Rumput Manan ',
                'scientific_name' => 'Cloeme rutidosperma',
                'description' => 'Rumput Manan  is a herb plant suitable for conservation and ecological restoration.',
                'price' => 10000,
                'image_url' => '',
                'plant_type' => 'Herb',
                'estimated_carbon' => '2-4 kg CO₂/th',
                'benefits' => 'Butterfly habitat',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Ketepeng ',
                'scientific_name' => 'Cassia alata ',
                'description' => 'Ketepeng  is a shrub plant suitable for conservation and ecological restoration.',
                'price' => 15000,
                'image_url' => '',
                'plant_type' => 'Shrub',
                'estimated_carbon' => '5-10 kg CO₂/th',
                'benefits' => 'Butterfly habitat',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Cempaka Kuning',
                'scientific_name' => 'Michelia champaca ',
                'description' => 'Cempaka Kuning is a tree plant suitable for conservation and ecological restoration.',
                'price' => 25000,
                'image_url' => '',
                'plant_type' => 'Tree',
                'estimated_carbon' => '30-50 kg CO₂/th',
                'benefits' => 'Butterfly habitat',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Jarak ',
                'scientific_name' => 'Ricinus communis ',
                'description' => 'Jarak  is a shrub plant suitable for conservation and ecological restoration.',
                'price' => 15000,
                'image_url' => '',
                'plant_type' => 'Shrub',
                'estimated_carbon' => '5-10 kg CO₂/th',
                'benefits' => 'Butterfly habitat',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Asystasia ',
                'scientific_name' => 'Asystasia intrusa',
                'description' => 'Asystasia  is a herb plant suitable for conservation and ecological restoration.',
                'price' => 10000,
                'image_url' => '',
                'plant_type' => 'Herb',
                'estimated_carbon' => '2-4 kg CO₂/th',
                'benefits' => 'Butterfly habitat',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Aristolochiae',
                'scientific_name' => 'Aristolochiae tagala ',
                'description' => 'Aristolochiae is a climber plant suitable for conservation and ecological restoration.',
                'price' => 12000,
                'image_url' => '',
                'plant_type' => 'Climber',
                'estimated_carbon' => '2-4 kg CO₂/th',
                'benefits' => 'Butterfly habitat',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Aristolochiae',
                'scientific_name' => 'Aristolochiae faveolata',
                'description' => 'Aristolochiae is a climber plant suitable for conservation and ecological restoration.',
                'price' => 12000,
                'image_url' => '',
                'plant_type' => 'Climber',
                'estimated_carbon' => '2-4 kg CO₂/th',
                'benefits' => 'Butterfly habitat',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Serut',
                'scientific_name' => 'Cerbera odollam ',
                'description' => 'Serut is a tree plant suitable for conservation and ecological restoration.',
                'price' => 25000,
                'image_url' => '',
                'plant_type' => 'Tree',
                'estimated_carbon' => '30-50 kg CO₂/th',
                'benefits' => 'Butterfly habitat',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Bunga Mentega',
                'scientific_name' => 'Nerium oleaner',
                'description' => 'Bunga Mentega is a shrub plant suitable for conservation and ecological restoration.',
                'price' => 15000,
                'image_url' => '',
                'plant_type' => 'Shrub',
                'estimated_carbon' => '5-10 kg CO₂/th',
                'benefits' => 'Butterfly habitat',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Daun Wungu ',
                'scientific_name' => 'Gratophyllum pictum',
                'description' => 'Daun Wungu  is a shrub plant suitable for conservation and ecological restoration.',
                'price' => 15000,
                'image_url' => '',
                'plant_type' => 'Shrub',
                'estimated_carbon' => '5-10 kg CO₂/th',
                'benefits' => 'Butterfly habitat',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Rumput Babi ',
                'scientific_name' => 'Synedrella nodiflora ',
                'description' => 'Rumput Babi  is a herb plant suitable for conservation and ecological restoration.',
                'price' => 10000,
                'image_url' => '',
                'plant_type' => 'Herb',
                'estimated_carbon' => '2-4 kg CO₂/th',
                'benefits' => 'Butterfly habitat',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Jelatang Ayam ',
                'scientific_name' => 'Laportea inerrupta',
                'description' => 'Jelatang Ayam  is a shrub plant suitable for conservation and ecological restoration.',
                'price' => 15000,
                'image_url' => '',
                'plant_type' => 'Shrub',
                'estimated_carbon' => '5-10 kg CO₂/th',
                'benefits' => 'Butterfly habitat',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Widuri ',
                'scientific_name' => 'Calotropis giganthea ',
                'description' => 'Widuri  is a shrub plant suitable for conservation and ecological restoration.',
                'price' => 15000,
                'image_url' => '',
                'plant_type' => 'Shrub',
                'estimated_carbon' => '5-10 kg CO₂/th',
                'benefits' => 'Butterfly habitat',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Lobi-Lobi ',
                'scientific_name' => 'Flacourtia inermis roxl.',
                'description' => 'Lobi-Lobi  is a tree plant suitable for conservation and ecological restoration.',
                'price' => 25000,
                'image_url' => '',
                'plant_type' => 'Tree',
                'estimated_carbon' => '30-50 kg CO₂/th',
                'benefits' => 'Butterfly habitat',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Ruku-Ruku Tetikus',
                'scientific_name' => 'Clausena excavata',
                'description' => 'Ruku-Ruku Tetikus is a tree plant suitable for conservation and ecological restoration.',
                'price' => 25000,
                'image_url' => '',
                'plant_type' => 'Tree',
                'estimated_carbon' => '30-50 kg CO₂/th',
                'benefits' => 'Butterfly habitat',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Ruku-Ruku Asli',
                'scientific_name' => 'Murraya koenigi',
                'description' => 'Ruku-Ruku Asli is a tree plant suitable for conservation and ecological restoration.',
                'price' => 25000,
                'image_url' => '',
                'plant_type' => 'Tree',
                'estimated_carbon' => '30-50 kg CO₂/th',
                'benefits' => 'Butterfly habitat',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Apama',
                'scientific_name' => 'Apama thomentosa',
                'description' => 'Apama is a shrub plant suitable for conservation and ecological restoration.',
                'price' => 15000,
                'image_url' => '',
                'plant_type' => 'Shrub',
                'estimated_carbon' => '5-10 kg CO₂/th',
                'benefits' => 'Butterfly habitat',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kelapa',
                'scientific_name' => 'Cocos nucifera',
                'description' => 'Kelapa is a tree plant suitable for conservation and ecological restoration.',
                'price' => 25000,
                'image_url' => '',
                'plant_type' => 'Tree',
                'estimated_carbon' => '15-25 kg CO₂/th',
                'benefits' => 'Butterfly habitat',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Ketapang',
                'scientific_name' => 'Terminalia catappa',
                'description' => 'Ketapang is a tree plant suitable for conservation and ecological restoration.',
                'price' => 25000,
                'image_url' => '',
                'plant_type' => 'Tree',
                'estimated_carbon' => '30-50 kg CO₂/th',
                'benefits' => 'Butterfly habitat',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Nona Makan Sirih',
                'scientific_name' => 'Mussaenda spp.',
                'description' => 'Nona Makan Sirih is a climber plant suitable for conservation and ecological restoration.',
                'price' => 12000,
                'image_url' => '',
                'plant_type' => 'Climber',
                'estimated_carbon' => '2-4 kg CO₂/th',
                'benefits' => 'Butterfly habitat',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Bungur',
                'scientific_name' => 'Lagerstromia soeciosa',
                'description' => 'Bungur is a tree plant suitable for conservation and ecological restoration.',
                'price' => 25000,
                'image_url' => '',
                'plant_type' => 'Tree',
                'estimated_carbon' => '30-50 kg CO₂/th',
                'benefits' => 'Butterfly habitat',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Tanaman Rambat Zemeros',
                'scientific_name' => 'Host Zemeros flegyas',
                'description' => 'Tanaman Rambat Zemeros is a shrub plant suitable for conservation and ecological restoration.',
                'price' => 15000,
                'image_url' => '',
                'plant_type' => 'Shrub',
                'estimated_carbon' => '5-10 kg CO₂/th',
                'benefits' => 'Butterfly habitat',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Pauh-Pauh',
                'scientific_name' => ' Melicoppe spp.',
                'description' => 'Pauh-Pauh is a tree plant suitable for conservation and ecological restoration.',
                'price' => 25000,
                'image_url' => '',
                'plant_type' => 'Tree',
                'estimated_carbon' => '30-50 kg CO₂/th',
                'benefits' => 'Butterfly habitat',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Bunga Asoka ',
                'scientific_name' => 'Ixora javanica ',
                'description' => 'Bunga Asoka  is a shrub plant suitable for conservation and ecological restoration.',
                'price' => 15000,
                'image_url' => '',
                'plant_type' => 'Shrub',
                'estimated_carbon' => '5-10 kg CO₂/th',
                'benefits' => 'Butterfly habitat',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Bunga Pagoda ',
                'scientific_name' => 'Clerodendrum paniculatum ',
                'description' => 'Bunga Pagoda  is a shrub plant suitable for conservation and ecological restoration.',
                'price' => 15000,
                'image_url' => '',
                'plant_type' => 'Shrub',
                'estimated_carbon' => '5-10 kg CO₂/th',
                'benefits' => 'Butterfly habitat',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Jengger Ayam ',
                'scientific_name' => 'Celosia argentea ',
                'description' => 'Jengger Ayam  is a shrub plant suitable for conservation and ecological restoration.',
                'price' => 15000,
                'image_url' => '',
                'plant_type' => 'Shrub',
                'estimated_carbon' => '5-10 kg CO₂/th',
                'benefits' => 'Butterfly habitat',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Bunga Tahi - Ayam ',
                'scientific_name' => 'Tagates erecta ',
                'description' => 'Bunga Tahi - Ayam  is a shrub plant suitable for conservation and ecological restoration.',
                'price' => 15000,
                'image_url' => '',
                'plant_type' => 'Shrub',
                'estimated_carbon' => '5-10 kg CO₂/th',
                'benefits' => 'Butterfly habitat',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kembang Pacar ',
                'scientific_name' => 'Impatiens balsamina ',
                'description' => 'Kembang Pacar  is a shrub plant suitable for conservation and ecological restoration.',
                'price' => 15000,
                'image_url' => '',
                'plant_type' => 'Shrub',
                'estimated_carbon' => '5-10 kg CO₂/th',
                'benefits' => 'Butterfly habitat',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Cente Manis ',
                'scientific_name' => 'Lantana camara ',
                'description' => 'Cente Manis  is a shrub plant suitable for conservation and ecological restoration.',
                'price' => 15000,
                'image_url' => '',
                'plant_type' => 'Shrub',
                'estimated_carbon' => '5-10 kg CO₂/th',
                'benefits' => 'Butterfly habitat',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Jarong ',
                'scientific_name' => 'Stachypheta indica ',
                'description' => 'Jarong  is a shrub plant suitable for conservation and ecological restoration.',
                'price' => 15000,
                'image_url' => '',
                'plant_type' => 'Shrub',
                'estimated_carbon' => '5-10 kg CO₂/th',
                'benefits' => 'Butterfly habitat',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kembang Pukul Empat ',
                'scientific_name' => 'Mirabilis jalapa ',
                'description' => 'Kembang Pukul Empat  is a shrub plant suitable for conservation and ecological restoration.',
                'price' => 15000,
                'image_url' => '',
                'plant_type' => 'Shrub',
                'estimated_carbon' => '5-10 kg CO₂/th',
                'benefits' => 'Butterfly habitat',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kembang Kertas ',
                'scientific_name' => 'Zinnia sp.',
                'description' => 'Kembang Kertas  is a shrub plant suitable for conservation and ecological restoration.',
                'price' => 15000,
                'image_url' => '',
                'plant_type' => 'Shrub',
                'estimated_carbon' => '5-10 kg CO₂/th',
                'benefits' => 'Butterfly habitat',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kembang Merak ',
                'scientific_name' => 'Caesalpinnia pulcherrima ',
                'description' => 'Kembang Merak  is a shrub plant suitable for conservation and ecological restoration.',
                'price' => 15000,
                'image_url' => '',
                'plant_type' => 'Shrub',
                'estimated_carbon' => '5-10 kg CO₂/th',
                'benefits' => 'Butterfly habitat',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Orok-Orok ',
                'scientific_name' => 'Crotalaria sriata',
                'description' => 'Orok-Orok  is a shrub plant suitable for conservation and ecological restoration.',
                'price' => 15000,
                'image_url' => '',
                'plant_type' => 'Shrub',
                'estimated_carbon' => '5-10 kg CO₂/th',
                'benefits' => 'Butterfly habitat',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kembang Sepatu',
                'scientific_name' => 'Hibiscus rosa-sinensis ',
                'description' => 'Kembang Sepatu is a shrub plant suitable for conservation and ecological restoration.',
                'price' => 15000,
                'image_url' => '',
                'plant_type' => 'Shrub',
                'estimated_carbon' => '5-10 kg CO₂/th',
                'benefits' => 'Butterfly habitat',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Cantik Manis ',
                'scientific_name' => 'Cosmos sulphurous cav',
                'description' => 'Cantik Manis  is a shrub plant suitable for conservation and ecological restoration.',
                'price' => 15000,
                'image_url' => '',
                'plant_type' => 'Shrub',
                'estimated_carbon' => '5-10 kg CO₂/th',
                'benefits' => 'Butterfly habitat',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Taiwan Beauty',
                'scientific_name' => 'Cuphea hysopifolia',
                'description' => 'Taiwan Beauty is a shrub plant suitable for conservation and ecological restoration.',
                'price' => 15000,
                'image_url' => '',
                'plant_type' => 'Shrub',
                'estimated_carbon' => '5-10 kg CO₂/th',
                'benefits' => 'Butterfly habitat',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Seruni',
                'scientific_name' => 'Widelia sp.',
                'description' => 'Seruni is a shrub plant suitable for conservation and ecological restoration.',
                'price' => 15000,
                'image_url' => '',
                'plant_type' => 'Shrub',
                'estimated_carbon' => '5-10 kg CO₂/th',
                'benefits' => 'Butterfly habitat',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kaliandra Merah ',
                'scientific_name' => 'Calliandra haemathocephala',
                'description' => 'Kaliandra Merah  is a tree plant suitable for conservation and ecological restoration.',
                'price' => 25000,
                'image_url' => '',
                'plant_type' => 'Tree',
                'estimated_carbon' => '30-50 kg CO₂/th',
                'benefits' => 'Butterfly habitat',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kaliandra Merah Putih',
                'scientific_name' => 'Calliandra surinamensis ',
                'description' => 'Kaliandra Merah Putih is a tree plant suitable for conservation and ecological restoration.',
                'price' => 25000,
                'image_url' => '',
                'plant_type' => 'Tree',
                'estimated_carbon' => '30-50 kg CO₂/th',
                'benefits' => 'Butterfly habitat',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kumis Kucing ',
                'scientific_name' => 'Oritthosiphon aristatus ',
                'description' => 'Kumis Kucing  is a shrub plant suitable for conservation and ecological restoration.',
                'price' => 15000,
                'image_url' => '',
                'plant_type' => 'Shrub',
                'estimated_carbon' => '5-10 kg CO₂/th',
                'benefits' => 'Butterfly habitat',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kembang Kancing ',
                'scientific_name' => 'Gomphrena globosa ',
                'description' => 'Kembang Kancing  is a shrub plant suitable for conservation and ecological restoration.',
                'price' => 15000,
                'image_url' => '',
                'plant_type' => 'Shrub',
                'estimated_carbon' => '5-10 kg CO₂/th',
                'benefits' => 'Butterfly habitat',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Micromelum',
                'scientific_name' => 'Micromelum minutum',
                'description' => 'Micromelum is a tree plant suitable for conservation and ecological restoration.',
                'price' => 25000,
                'image_url' => '',
                'plant_type' => 'Tree',
                'estimated_carbon' => '30-50 kg CO₂/th',
                'benefits' => 'Butterfly habitat',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Keruing',
                'scientific_name' => 'Dipterocarpus alatus',
                'description' => 'Keruing is a tree plant suitable for conservation and ecological restoration.',
                'price' => 25000,
                'image_url' => '',
                'plant_type' => 'Tree',
                'estimated_carbon' => '50-80 kg CO₂/th',
                'benefits' => 'Habitat primata & burung; pakan tupai',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Keruing Kancing',
                'scientific_name' => 'Dipterocarpus hasseltii',
                'description' => 'Keruing Kancing is a tree plant suitable for conservation and ecological restoration.',
                'price' => 25000,
                'image_url' => '',
                'plant_type' => 'Tree',
                'estimated_carbon' => '45-75 kg CO₂/th',
                'benefits' => 'Pohon induk untuk burung noktural',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Keruing Kaloi',
                'scientific_name' => 'Dipterocarpus gracilis',
                'description' => 'Keruing Kaloi is a tree plant suitable for conservation and ecological restoration.',
                'price' => 25000,
                'image_url' => '',
                'plant_type' => 'Tree',
                'estimated_carbon' => '40-70 kg CO₂/th',
                'benefits' => 'Kritis untuk Orangutan; sarang burung',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Meranti Bakau',
                'scientific_name' => 'Shorea leprosula',
                'description' => 'Meranti Bakau is a tree plant suitable for conservation and ecological restoration.',
                'price' => 25000,
                'image_url' => '',
                'plant_type' => 'Tree',
                'estimated_carbon' => '50-85 kg CO₂/th',
                'benefits' => 'Pakan primata; habitat burung hantu',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Meranti Rawa',
                'scientific_name' => 'Shorea parvifolia',
                'description' => 'Meranti Rawa is a tree plant suitable for conservation and ecological restoration.',
                'price' => 25000,
                'image_url' => '',
                'plant_type' => 'Tree',
                'estimated_carbon' => '45-75 kg CO₂/th',
                'benefits' => 'Koridor satwa liar',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Meranti Payung',
                'scientific_name' => 'Shorea macrophylla',
                'description' => 'Meranti Payung is a tree plant suitable for conservation and ecological restoration.',
                'price' => 25000,
                'image_url' => '',
                'plant_type' => 'Tree',
                'estimated_carbon' => '40-70 kg CO₂/th',
                'benefits' => 'Pohon pakan gajah sumatera',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kapur',
                'scientific_name' => 'Dryobalanops lanceolata',
                'description' => 'Kapur is a tree plant suitable for conservation and ecological restoration.',
                'price' => 25000,
                'image_url' => '',
                'plant_type' => 'Tree',
                'estimated_carbon' => '45-70 kg CO₂/th',
                'benefits' => 'Habitat burung insectivora',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Merawan',
                'scientific_name' => 'Hopea odorata',
                'description' => 'Merawan is a tree plant suitable for conservation and ecological restoration.',
                'price' => 25000,
                'image_url' => '',
                'plant_type' => 'Tree',
                'estimated_carbon' => '35-60 kg CO₂/th',
                'benefits' => 'Pohon koridor mamalia',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Mersawa',
                'scientific_name' => 'Anisoptera costata',
                'description' => 'Mersawa is a tree plant suitable for conservation and ecological restoration.',
                'price' => 25000,
                'image_url' => '',
                'plant_type' => 'Tree',
                'estimated_carbon' => '40-65 kg CO₂/th',
                'benefits' => 'Pakan tupai dan trenggiling',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Resak Rawa',
                'scientific_name' => 'Vatica pumila',
                'description' => 'Resak Rawa is a tree plant suitable for conservation and ecological restoration.',
                'price' => 25000,
                'image_url' => '',
                'plant_type' => 'Tree',
                'estimated_carbon' => '35-55 kg CO₂/th',
                'benefits' => 'Habitat burung air rawa',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Beringin',
                'scientific_name' => 'Ficus benjamina',
                'description' => 'Beringin is a tree plant suitable for conservation and ecological restoration.',
                'price' => 25000,
                'image_url' => '',
                'plant_type' => 'Tree',
                'estimated_carbon' => '25-45 kg CO₂/th',
                'benefits' => 'Kritis untuk 50+ spesies burung; sarang kelelawar',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Ara Sren',
                'scientific_name' => 'Ficus virens',
                'description' => 'Ara Sren is a tree plant suitable for conservation and ecological restoration.',
                'price' => 25000,
                'image_url' => '',
                'plant_type' => 'Tree',
                'estimated_carbon' => '30-50 kg CO₂/th',
                'benefits' => 'Pakan burung frugivora & primata',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Ara',
                'scientific_name' => 'Ficus religiosa',
                'description' => 'Ara is a tree plant suitable for conservation and ecological restoration.',
                'price' => 25000,
                'image_url' => '',
                'plant_type' => 'Tree',
                'estimated_carbon' => '25-40 kg CO₂/th',
                'benefits' => 'Habitat kupu-kupu & burung',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Ara Jawa',
                'scientific_name' => 'Ficus hispida',
                'description' => 'Ara Jawa is a tree plant suitable for conservation and ecological restoration.',
                'price' => 25000,
                'image_url' => '',
                'plant_type' => 'Tree',
                'estimated_carbon' => '20-35 kg CO₂/th',
                'benefits' => 'Pakan biawak & burung',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Jati',
                'scientific_name' => 'Tectona grandis',
                'description' => 'Jati is a tree plant suitable for conservation and ecological restoration.',
                'price' => 25000,
                'image_url' => '',
                'plant_type' => 'Tree',
                'estimated_carbon' => '35-55 kg CO₂/th',
                'benefits' => 'Pohon kelelawar & tupai',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Angsana',
                'scientific_name' => 'Pterocarpus indicus',
                'description' => 'Angsana is a tree plant suitable for conservation and ecological restoration.',
                'price' => 25000,
                'image_url' => '',
                'plant_type' => 'Tree',
                'estimated_carbon' => '45-75 kg CO₂/th',
                'benefits' => 'Habitat burung air',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Nan',
                'scientific_name' => 'Murraya koenigii',
                'description' => 'Nan is a tree plant suitable for conservation and ecological restoration.',
                'price' => 25000,
                'image_url' => '',
                'plant_type' => 'Tree',
                'estimated_carbon' => 'nan',
                'benefits' => 'nan',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Nan',
                'scientific_name' => 'Glycosmis penthapilla',
                'description' => 'Nan is a tree plant suitable for conservation and ecological restoration.',
                'price' => 25000,
                'image_url' => '',
                'plant_type' => 'Tree',
                'estimated_carbon' => 'nan',
                'benefits' => 'nan',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Eucalyptus',
                'scientific_name' => 'Eucalyptus deglupta',
                'description' => 'Eucalyptus is a tree plant suitable for conservation and ecological restoration.',
                'price' => 25000,
                'image_url' => '',
                'plant_type' => 'Tree',
                'estimated_carbon' => '50-80 kg CO₂/th',
                'benefits' => 'Pohon madu untuk lebah & burung',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Durian',
                'scientific_name' => 'Durio zibethinus',
                'description' => 'Durian is a tree plant suitable for conservation and ecological restoration.',
                'price' => 25000,
                'image_url' => '',
                'plant_type' => 'Tree',
                'estimated_carbon' => '30-50 kg CO₂/th',
                'benefits' => 'Kritis untuk primata (Orangutan, kera); burung',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Sukun',
                'scientific_name' => 'Artocarpus altilis',
                'description' => 'Sukun is a tree plant suitable for conservation and ecological restoration.',
                'price' => 25000,
                'image_url' => '',
                'plant_type' => 'Tree',
                'estimated_carbon' => '20-35 kg CO₂/th',
                'benefits' => 'Pakan kelelawar pemakan buah',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Mangga',
                'scientific_name' => 'Mangifera indica',
                'description' => 'Mangga is a tree plant suitable for conservation and ecological restoration.',
                'price' => 25000,
                'image_url' => '',
                'plant_type' => 'Tree',
                'estimated_carbon' => '20-35 kg CO₂/th',
                'benefits' => 'Pakan tupai & kera',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Rambutan',
                'scientific_name' => 'Nephelium lappaceum',
                'description' => 'Rambutan is a tree plant suitable for conservation and ecological restoration.',
                'price' => 25000,
                'image_url' => '',
                'plant_type' => 'Tree',
                'estimated_carbon' => '15-30 kg CO₂/th',
                'benefits' => 'Pakan burung frugivora',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Jambu Biji',
                'scientific_name' => 'Psidium guajava',
                'description' => 'Jambu Biji is a tree plant suitable for conservation and ecological restoration.',
                'price' => 25000,
                'image_url' => '',
                'plant_type' => 'Tree',
                'estimated_carbon' => '15-25 kg CO₂/th',
                'benefits' => 'Pakan mamalia kecil; kupu-kupu',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Jambu Air',
                'scientific_name' => 'Syzygium aqueum',
                'description' => 'Jambu Air is a tree plant suitable for conservation and ecological restoration.',
                'price' => 25000,
                'image_url' => '',
                'plant_type' => 'Tree',
                'estimated_carbon' => '15-25 kg CO₂/th',
                'benefits' => 'Pakan burung & kelelawar',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Duwet',
                'scientific_name' => 'Syzygium cumini',
                'description' => 'Duwet is a tree plant suitable for conservation and ecological restoration.',
                'price' => 25000,
                'image_url' => '',
                'plant_type' => 'Tree',
                'estimated_carbon' => '20-30 kg CO₂/th',
                'benefits' => 'Pakan trenggiling',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Belimbing Wuluh',
                'scientific_name' => 'Averrhoa bilimbi',
                'description' => 'Belimbing Wuluh is a tree plant suitable for conservation and ecological restoration.',
                'price' => 25000,
                'image_url' => '',
                'plant_type' => 'Tree',
                'estimated_carbon' => '10-20 kg CO₂/th',
                'benefits' => 'Pakan burung & kupu-kupu',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Belimbing',
                'scientific_name' => 'Averrhoa carambola',
                'description' => 'Belimbing is a tree plant suitable for conservation and ecological restoration.',
                'price' => 25000,
                'image_url' => '',
                'plant_type' => 'Tree',
                'estimated_carbon' => '10-20 kg CO₂/th',
                'benefits' => 'Nektar untuk kupu-kupu',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Pisang',
                'scientific_name' => 'Musa spp.',
                'description' => 'Pisang is a tree plant suitable for conservation and ecological restoration.',
                'price' => 25000,
                'image_url' => '',
                'plant_type' => 'Tree',
                'estimated_carbon' => '10-18 kg CO₂/th',
                'benefits' => 'Pakan trenggiling, burung, kupu-kupu',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kayu Manis',
                'scientific_name' => 'Cinnamomum verum',
                'description' => 'Kayu Manis is a tree plant suitable for conservation and ecological restoration.',
                'price' => 25000,
                'image_url' => '',
                'plant_type' => 'Tree',
                'estimated_carbon' => '20-30 kg CO₂/th',
                'benefits' => 'Habitat serangga parasitoid',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Andaliman',
                'scientific_name' => 'Zanthoxylum rhetsa',
                'description' => 'Andaliman is a tree plant suitable for conservation and ecological restoration.',
                'price' => 25000,
                'image_url' => '',
                'plant_type' => 'Tree',
                'estimated_carbon' => '15-25 kg CO₂/th',
                'benefits' => 'Pakan burung',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kenanga',
                'scientific_name' => 'Cananga odorata',
                'description' => 'Kenanga is a tree plant suitable for conservation and ecological restoration.',
                'price' => 25000,
                'image_url' => '',
                'plant_type' => 'Tree',
                'estimated_carbon' => '15-25 kg CO₂/th',
                'benefits' => 'Nektar untuk kupu-kupu & burung',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Cendana',
                'scientific_name' => 'Santalum album',
                'description' => 'Cendana is a tree plant suitable for conservation and ecological restoration.',
                'price' => 25000,
                'image_url' => '',
                'plant_type' => 'Tree',
                'estimated_carbon' => '12-20 kg CO₂/th',
                'benefits' => 'Habitat kupu-kupu langka',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Aren',
                'scientific_name' => 'Arenga pinnata',
                'description' => 'Aren is a tree plant suitable for conservation and ecological restoration.',
                'price' => 25000,
                'image_url' => '',
                'plant_type' => 'Tree',
                'estimated_carbon' => '15-25 kg CO₂/th',
                'benefits' => 'Pakan tarsius; habitat tupai; nektar',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kelapa',
                'scientific_name' => 'Cocos nucifera',
                'description' => 'Kelapa is a tree plant suitable for conservation and ecological restoration.',
                'price' => 25000,
                'image_url' => '',
                'plant_type' => 'Tree',
                'estimated_carbon' => '20-35 kg CO₂/th',
                'benefits' => 'Habitat burung sarang (Murai, jalak); serangga',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Lontar',
                'scientific_name' => 'Borassus flabellifer',
                'description' => 'Lontar is a tree plant suitable for conservation and ecological restoration.',
                'price' => 25000,
                'image_url' => '',
                'plant_type' => 'Tree',
                'estimated_carbon' => '15-25 kg CO₂/th',
                'benefits' => 'Pakan luwak; sarang burung',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Nipah',
                'scientific_name' => 'Nypa fruticans',
                'description' => 'Nipah is a tree plant suitable for conservation and ecological restoration.',
                'price' => 25000,
                'image_url' => '',
                'plant_type' => 'Tree',
                'estimated_carbon' => '25-45 kg CO₂/th',
                'benefits' => 'Habitat burung air & serangga rawa',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Pinang',
                'scientific_name' => 'Areca catechu',
                'description' => 'Pinang is a tree plant suitable for conservation and ecological restoration.',
                'price' => 25000,
                'image_url' => '',
                'plant_type' => 'Tree',
                'estimated_carbon' => '10-20 kg CO₂/th',
                'benefits' => 'Habitat mamalia kecil',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Bambu Tali',
                'scientific_name' => 'Gigantochloa apus',
                'description' => 'Bambu Tali is a bamboo plant suitable for conservation and ecological restoration.',
                'price' => 30000,
                'image_url' => '',
                'plant_type' => 'Bamboo',
                'estimated_carbon' => 'Tinggi',
                'benefits' => 'Habitat trenggiling & tupai; koridor mamalia',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Bambu Ater',
                'scientific_name' => 'Gigantochloa verticillata',
                'description' => 'Bambu Ater is a bamboo plant suitable for conservation and ecological restoration.',
                'price' => 30000,
                'image_url' => '',
                'plant_type' => 'Bamboo',
                'estimated_carbon' => 'Tinggi',
                'benefits' => 'Habitat burung & kelelawar',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Bambu Betung',
                'scientific_name' => 'Dendrocalamus asper',
                'description' => 'Bambu Betung is a bamboo plant suitable for conservation and ecological restoration.',
                'price' => 30000,
                'image_url' => '',
                'plant_type' => 'Bamboo',
                'estimated_carbon' => 'Tinggi',
                'benefits' => 'Habitat biawak & serangga',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Bambu Kuning',
                'scientific_name' => 'Bambusa vulgaris',
                'description' => 'Bambu Kuning is a bamboo plant suitable for conservation and ecological restoration.',
                'price' => 30000,
                'image_url' => '',
                'plant_type' => 'Bamboo',
                'estimated_carbon' => 'Tinggi',
                'benefits' => 'Habitat burung (pendara)',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Bambu Reng',
                'scientific_name' => 'Schizostachyum brachycladum',
                'description' => 'Bambu Reng is a bamboo plant suitable for conservation and ecological restoration.',
                'price' => 30000,
                'image_url' => '',
                'plant_type' => 'Bamboo',
                'estimated_carbon' => 'Tinggi',
                'benefits' => 'Habitat kupu-kupu & burung',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Nusa Indah',
                'scientific_name' => 'Mussaenda spp.',
                'description' => 'Nusa Indah is a shrub plant suitable for conservation and ecological restoration.',
                'price' => 15000,
                'image_url' => '',
                'plant_type' => 'Shrub',
                'estimated_carbon' => '5-10 kg CO₂/th',
                'benefits' => 'Host plant kupu-kupu (Ornithoptera)',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Asoka',
                'scientific_name' => 'Ixora spp.',
                'description' => 'Asoka is a shrub plant suitable for conservation and ecological restoration.',
                'price' => 15000,
                'image_url' => '',
                'plant_type' => 'Shrub',
                'estimated_carbon' => '5-10 kg CO₂/th',
                'benefits' => 'Host & food plant kupu-kupu (Papilionidae)',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Girang',
                'scientific_name' => 'Leea indica',
                'description' => 'Girang is a shrub plant suitable for conservation and ecological restoration.',
                'price' => 15000,
                'image_url' => '',
                'plant_type' => 'Shrub',
                'estimated_carbon' => '4-8 kg CO₂/th',
                'benefits' => 'Pakan burung frugivora',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Senggani',
                'scientific_name' => 'Melastoma malabathricum',
                'description' => 'Senggani is a shrub plant suitable for conservation and ecological restoration.',
                'price' => 15000,
                'image_url' => '',
                'plant_type' => 'Shrub',
                'estimated_carbon' => '3-7 kg CO₂/th',
                'benefits' => 'Pakan burung; habitat kupu-kupu',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Akar Kupang',
                'scientific_name' => 'Rubus moluccanus',
                'description' => 'Akar Kupang is a shrub plant suitable for conservation and ecological restoration.',
                'price' => 15000,
                'image_url' => '',
                'plant_type' => 'Shrub',
                'estimated_carbon' => '3-6 kg CO₂/th',
                'benefits' => 'Pakan mamalia kecil & burung',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kopi Hutan',
                'scientific_name' => 'Psychotria spp.',
                'description' => 'Kopi Hutan is a shrub plant suitable for conservation and ecological restoration.',
                'price' => 15000,
                'image_url' => '',
                'plant_type' => 'Shrub',
                'estimated_carbon' => '4-8 kg CO₂/th',
                'benefits' => 'Habitat burung hutan',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kembang Bugang',
                'scientific_name' => 'Clerodendrum spp.',
                'description' => 'Kembang Bugang is a shrub plant suitable for conservation and ecological restoration.',
                'price' => 15000,
                'image_url' => '',
                'plant_type' => 'Shrub',
                'estimated_carbon' => '5-10 kg CO₂/th',
                'benefits' => 'Nektar kupu-kupu & burung',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Tanjung',
                'scientific_name' => 'Stachytarpheta indica',
                'description' => 'Tanjung is a shrub plant suitable for conservation and ecological restoration.',
                'price' => 15000,
                'image_url' => '',
                'plant_type' => 'Shrub',
                'estimated_carbon' => '3-6 kg CO₂/th',
                'benefits' => 'Nektar untuk kupu-kupu',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Bulu Ayam',
                'scientific_name' => 'Eupatorium odoratum',
                'description' => 'Bulu Ayam is a shrub plant suitable for conservation and ecological restoration.',
                'price' => 15000,
                'image_url' => '',
                'plant_type' => 'Shrub',
                'estimated_carbon' => '4-8 kg CO₂/th',
                'benefits' => 'Habitat serangga parasitoid',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Tembelekan',
                'scientific_name' => 'Lantana camara',
                'description' => 'Tembelekan is a shrub plant suitable for conservation and ecological restoration.',
                'price' => 15000,
                'image_url' => '',
                'plant_type' => 'Shrub',
                'estimated_carbon' => '3-5 kg CO₂/th',
                'benefits' => 'Nektar untuk kupu-kupu',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Ki Asem',
                'scientific_name' => 'Sambucus javanica',
                'description' => 'Ki Asem is a shrub plant suitable for conservation and ecological restoration.',
                'price' => 15000,
                'image_url' => '',
                'plant_type' => 'Shrub',
                'estimated_carbon' => '5-10 kg CO₂/th',
                'benefits' => 'Pakan burung',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kaliandra',
                'scientific_name' => 'Calliandra calothyrsus',
                'description' => 'Kaliandra is a shrub plant suitable for conservation and ecological restoration.',
                'price' => 15000,
                'image_url' => '',
                'plant_type' => 'Shrub',
                'estimated_carbon' => '8-15 kg CO₂/th',
                'benefits' => 'Nitrogen fixer; pakan burung & mamalia',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Gamal',
                'scientific_name' => 'Gliricidia sepium',
                'description' => 'Gamal is a shrub plant suitable for conservation and ecological restoration.',
                'price' => 15000,
                'image_url' => '',
                'plant_type' => 'Shrub',
                'estimated_carbon' => '8-15 kg CO₂/th',
                'benefits' => 'Nitrogen fixer; host vanilla; pakan rusa',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Lamtoro',
                'scientific_name' => 'Leucaena leucocephala',
                'description' => 'Lamtoro is a shrub plant suitable for conservation and ecological restoration.',
                'price' => 15000,
                'image_url' => '',
                'plant_type' => 'Shrub',
                'estimated_carbon' => '7-14 kg CO₂/th',
                'benefits' => 'Pakan mamalia & burung; nitrogen fixer',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Dadap',
                'scientific_name' => 'Erythrina variegata',
                'description' => 'Dadap is a shrub plant suitable for conservation and ecological restoration.',
                'price' => 15000,
                'image_url' => '',
                'plant_type' => 'Shrub',
                'estimated_carbon' => '8-15 kg CO₂/th',
                'benefits' => 'Nektar untuk burung; nitrogen fixer',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Turi',
                'scientific_name' => 'Sesbania grandiflora',
                'description' => 'Turi is a shrub plant suitable for conservation and ecological restoration.',
                'price' => 15000,
                'image_url' => '',
                'plant_type' => 'Shrub',
                'estimated_carbon' => '6-12 kg CO₂/th',
                'benefits' => 'Pakan burung & serangga polinator',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Mengkudu',
                'scientific_name' => 'Morinda citrifolia',
                'description' => 'Mengkudu is a shrub plant suitable for conservation and ecological restoration.',
                'price' => 15000,
                'image_url' => '',
                'plant_type' => 'Shrub',
                'estimated_carbon' => '4-8 kg CO₂/th',
                'benefits' => 'Pakan luwak & burung; host kupu-kupu',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Sirih Hutan',
                'scientific_name' => 'Piper aduncum',
                'description' => 'Sirih Hutan is a shrub plant suitable for conservation and ecological restoration.',
                'price' => 15000,
                'image_url' => '',
                'plant_type' => 'Shrub',
                'estimated_carbon' => '3-6 kg CO₂/th',
                'benefits' => 'Pakan trenggiling',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Sirih',
                'scientific_name' => 'Piper betle',
                'description' => 'Sirih is a tree plant suitable for conservation and ecological restoration.',
                'price' => 25000,
                'image_url' => '',
                'plant_type' => 'Tree',
                'estimated_carbon' => '2-5 kg CO₂/th',
                'benefits' => 'Habitat serangga kecil',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Jahe-Jahean',
                'scientific_name' => 'Zingiber spp.',
                'description' => 'Jahe-Jahean is a herb plant suitable for conservation and ecological restoration.',
                'price' => 10000,
                'image_url' => '',
                'plant_type' => 'Herb',
                'estimated_carbon' => '2-4 kg CO₂/th',
                'benefits' => 'Nektar untuk kupu-kupu & burung',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Hoya',
                'scientific_name' => 'Hoya spp.',
                'description' => 'Hoya is a climber plant suitable for conservation and ecological restoration.',
                'price' => 12000,
                'image_url' => '',
                'plant_type' => 'Climber',
                'estimated_carbon' => '5-8 kg CO₂/th',
                'benefits' => 'Pakan Kupu-kupu',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Markisa/Rambusa',
                'scientific_name' => 'Passiflora spp.',
                'description' => 'Markisa/Rambusa is a climber plant suitable for conservation and ecological restoration.',
                'price' => 12000,
                'image_url' => '',
                'plant_type' => 'Climber',
                'estimated_carbon' => '3-6 kg CO₂/th',
                'benefits' => 'Pakan Kupu-kupu',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Rambusa',
                'scientific_name' => 'Adenia spp.',
                'description' => 'Rambusa is a climber plant suitable for conservation and ecological restoration.',
                'price' => 12000,
                'image_url' => '',
                'plant_type' => 'Climber',
                'estimated_carbon' => '2-5 kg CO₂/th',
                'benefits' => 'Pakan Kupu-kupu',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Begawan',
                'scientific_name' => 'Cissus spp.',
                'description' => 'Begawan is a climber plant suitable for conservation and ecological restoration.',
                'price' => 12000,
                'image_url' => '',
                'plant_type' => 'Climber',
                'estimated_carbon' => '2-4 kg CO₂/th',
                'benefits' => 'Pakan burung & mamalia',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Akar Setawar',
                'scientific_name' => 'Smilax spp.',
                'description' => 'Akar Setawar is a climber plant suitable for conservation and ecological restoration.',
                'price' => 12000,
                'image_url' => '',
                'plant_type' => 'Climber',
                'estimated_carbon' => '2-4 kg CO₂/th',
                'benefits' => 'Pakan mamalia kecil',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Rotan',
                'scientific_name' => 'Calamus spp.',
                'description' => 'Rotan is a tree plant suitable for conservation and ecological restoration.',
                'price' => 25000,
                'image_url' => '',
                'plant_type' => 'Tree',
                'estimated_carbon' => '8-15 kg CO₂/th',
                'benefits' => 'Habitat trenggiling & burung',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Rotan Tikus',
                'scientific_name' => 'Korthalsia spp.',
                'description' => 'Rotan Tikus is a climber plant suitable for conservation and ecological restoration.',
                'price' => 12000,
                'image_url' => '',
                'plant_type' => 'Climber',
                'estimated_carbon' => '6-12 kg CO₂/th',
                'benefits' => 'Habitat mamalia kecil',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Akar Takut',
                'scientific_name' => 'Flagellaria indica',
                'description' => 'Akar Takut is a climber plant suitable for conservation and ecological restoration.',
                'price' => 12000,
                'image_url' => '',
                'plant_type' => 'Climber',
                'estimated_carbon' => '2-4 kg CO₂/th',
                'benefits' => 'Habitat kupu-kupu',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Ubi Rambat',
                'scientific_name' => 'Ipomoea batatas',
                'description' => 'Ubi Rambat is a climber plant suitable for conservation and ecological restoration.',
                'price' => 12000,
                'image_url' => '',
                'plant_type' => 'Climber',
                'estimated_carbon' => '2-4 kg CO₂/th',
                'benefits' => 'Pakan babi hutan',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Lengkuas',
                'scientific_name' => 'Alpinia galanga',
                'description' => 'Lengkuas is a herb plant suitable for conservation and ecological restoration.',
                'price' => 10000,
                'image_url' => '',
                'plant_type' => 'Herb',
                'estimated_carbon' => '2-4 kg CO₂/th',
                'benefits' => 'Nektar untuk kupu-kupu',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kunyit',
                'scientific_name' => 'Curcuma longa',
                'description' => 'Kunyit is a herb plant suitable for conservation and ecological restoration.',
                'price' => 10000,
                'image_url' => '',
                'plant_type' => 'Herb',
                'estimated_carbon' => '1-3 kg CO₂/th',
                'benefits' => 'Habitat serangga tanah',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Kecombrang',
                'scientific_name' => 'Etlingera elatior',
                'description' => 'Kecombrang is a herb plant suitable for conservation and ecological restoration.',
                'price' => 10000,
                'image_url' => '',
                'plant_type' => 'Herb',
                'estimated_carbon' => '2-4 kg CO₂/th',
                'benefits' => 'Nektar untuk burung kolibri',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Pisang-Pisangan',
                'scientific_name' => 'Heliconia spp.',
                'description' => 'Pisang-Pisangan is a herb plant suitable for conservation and ecological restoration.',
                'price' => 10000,
                'image_url' => '',
                'plant_type' => 'Herb',
                'estimated_carbon' => '2-5 kg CO₂/th',
                'benefits' => 'Habitat kupu-kupu & burung',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Pacing',
                'scientific_name' => 'Costus speciosus',
                'description' => 'Pacing is a herb plant suitable for conservation and ecological restoration.',
                'price' => 10000,
                'image_url' => '',
                'plant_type' => 'Herb',
                'estimated_carbon' => '2-4 kg CO₂/th',
                'benefits' => 'Nektar kupu-kupu',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Bengkarung',
                'scientific_name' => 'Thalia geniculata',
                'description' => 'Bengkarung is a tree plant suitable for conservation and ecological restoration.',
                'price' => 25000,
                'image_url' => '',
                'plant_type' => 'Tree',
                'estimated_carbon' => '3-6 kg CO₂/th',
                'benefits' => 'Habitat burung air & serangga',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Jukut/Jerami',
                'scientific_name' => 'Cyperus spp.',
                'description' => 'Jukut/Jerami is a herb plant suitable for conservation and ecological restoration.',
                'price' => 10000,
                'image_url' => '',
                'plant_type' => 'Herb',
                'estimated_carbon' => '1-3 kg CO₂/th',
                'benefits' => 'Habitat mamalia kecil & serangga',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Alang-Alang',
                'scientific_name' => 'Imperata cylindrica',
                'description' => 'Alang-Alang is a herb plant suitable for conservation and ecological restoration.',
                'price' => 10000,
                'image_url' => '',
                'plant_type' => 'Herb',
                'estimated_carbon' => '2-5 kg CO₂/th',
                'benefits' => 'Habitat mamalia kecil',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Prumpung',
                'scientific_name' => 'Phragmites karka',
                'description' => 'Prumpung is a tree plant suitable for conservation and ecological restoration.',
                'price' => 25000,
                'image_url' => '',
                'plant_type' => 'Tree',
                'estimated_carbon' => '2-5 kg CO₂/th',
                'benefits' => 'Habitat burung air & serangga',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'name' => 'Rumput Hutan',
                'scientific_name' => 'Scleria sumatrensis',
                'description' => 'Rumput Hutan is a herb plant suitable for conservation and ecological restoration.',
                'price' => 10000,
                'image_url' => '',
                'plant_type' => 'Herb',
                'estimated_carbon' => '1-3 kg CO₂/th',
                'benefits' => 'Habitat serangga & kupu-kupu',
                'soft_delete' => 0,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

        ]);
    }
}
